name: Build and Deploy MERN App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3. Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # 4. Install frontend dependencies & build
      - name: Install frontend dependencies & build
        run: |
          cd frontend
          npm install
          CI=false npm run build

      # 5. Copy frontend build into backend (so Express can serve it)
      - name: Move frontend build to backend
        run: |
          cp -r frontend/build backend/

      # 6. Zip backend folder (with frontend/build inside)
      - name: Prepare deployment package
        run: |
          cd backend
          zip -r ../deployment.zip ./*

      # 7. Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # 8. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'taskify-project-app'
          package: deployment.zip
